# Site settings
title: Fake News
email: example@epfl.ch
url: https://gjemsvoldrahm.github.io/
description: "Data story on fake news for the class CS401 - Applied Data Analysis at EPFL."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  # RGB code: (33,154,179)
  links: '#219ab3' #'#ed1c24'
  template_sec1: rgb(173, 190, 207)
  template_sec2: rgb(225, 225, 225)

# Footer settings
footer: Gjems, Vold & Rahm

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/Benjamin-Rahm/ADA2018-Project-gjems_rahm_vold

# Build settings
markdown: kramdown
permalink: pretty
